services:
  canvas:
    build:
      context: .
      dockerfile: Dockerfile
      target: canvas
    env_file:
      - canvas_project/.env

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - canvas
