services:
  canvas:
    build:
      context: .
      dockerfile: Dockerfile
      target: canvas
    volumes:
      - media_volume:/canvas/media
    env_file:
      - canvas_project/.env

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
    volumes:
      - media_volume:/usr/share/nginx/html/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - canvas

volumes:
  media_volume:
