# Generated by Django 5.1.6 on 2025-02-07 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_interface", "0002_job_project"),
        ("project_management", "0023_receiver_receiver_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="project_management.project",
            ),
        ),
    ]
