# Generated by Django 5.2.3 on 2025-08-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    """Alter 'favorite' field in Project model from CharField to BooleanField."""

    dependencies = [
        ("project_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="favorite",
            field=models.BooleanField(default=False),
        ),
    ]
