"""Contains paths to files."""

default_profile_pic = "img/profile_pics/default.svg"
"""Path to the default profile picture."""
register_template = "account_management/register.html"
"""Path to the registration template."""
login_template = "account_management/login.html"
"""Path to the login template."""
confirm_deletion_template = "account_management/confirm_deletion.html"
"""Path to the account deletion confirmation template."""
password_reset_template = "account_management/password_reset.html"
"""Path to the password reset template."""
invalid_link_template = "account_management/invalid_link.html"
"""Path to the invalid link template."""
password_forgotten_template = "account_management/password_forgotten.html"
"""Path to the password forgotten template."""
profile_picture_jpg = "profile_picture.jpg"
"""Path to the profile picture in JPEG format."""
profile_picture_content_type = "image/jpeg"
old_profile_picture_jpg = "old_profile_picture.jpg"
new_profile_picture_jpg = "new_profile_picture.jpg"
register_template = "account_management/register.html"
"""Path to the registration template."""
login_template = "account_management/login.html"
"""Path to the login template."""
confirm_deletion_template = "account_management/confirm_deletion.html"
"""Path to the account deletion confirmation template."""
password_reset_template = "account_management/password_reset.html"
"""Path to the password reset template."""
invalid_link_template = "account_management/invalid_link.html"
"""Path to the invalid link template."""
password_forgotten_template = "account_management/password_forgotten.html"
"""Path to the password forgotten template."""
profile_picture_jpg = "profile_picture.jpg"
"""Path to the profile picture in JPEG format."""
profile_picture_content_type = "image/jpeg"
old_profile_picture_jpg = "old_profile_picture.jpg"
new_profile_picture_jpg = "new_profile_picture.jpg"
SCENARIO_FILE_SUFFIX = "ScenarioFile"
SCENARIO_EXT = ".h5"


# Constants for HDF5 file paths
TEST_STRAL_DATA_PATH = "hdf5_management/data/test_stral_data.binp"
