# Generated by Django 5.1.4 on 2025-02-05 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_interface_mockup", "0001_initial"),
        ("project_management", "0018_merge_20250205_1112"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="project_management.project",
            ),
        ),
    ]
