# Constants for testing account management features in a Canvas project

TEST_EMAIL = "testuser@example.com"
TEST_USERNAME = "testuser"
SECURE_PASSWORD = "SecurePass123!"
TOO_SHORT_PASSWORD = "Save-1"
TEST_PASSWORD = "test"
UPDATED_PASSWORD = "NewSecurePassword123!"
RESET_PASSWORD = "SecurePass1234!"
NO_SPECIAL_CHAR_PASSWORD = "SecurePass123"
COMPLETELY_WRONG_PASSWORD = "securepassword"
NO_UPPERCASE_PASSWORD = "securepassword123!"
NO_LOWERCASE_PASSWORD = "SECUREPASSWORD123!"
MISMATCHED_BUT_CORRECT_PASSWORD = "NewSecurePassword123!!"
NO_NUMERIC_PASSWORD = "SecurePassword!"
MISMATCHED_BUT_CORRECT_PASSWORD_2 = "NewSecurePassword123!!!"
WRONG_LOGIN_PASSWORD = "WrongPassword123!"
TEST_EMAIL = "test@mail.de"
TEST_FIRST_NAME = "test_first_name"
TEST_LAST_NAME = "test_last_name"
TEST2_FIRST_NAME = "test2_first_name"
TEST2_LAST_NAME = "test2_last_name"
TEST2_EMAIL = "test2@mail.de"
MAX_EMAIL = "max@mail.de"
TEST3_EMAIL = "test3@example.com"
TEST_USERNAME = "testuser"
NEW_TEST_EMAIL = "new_test@mail.de"
NEW_TEST_FIRST_NAME = "new_first_name"
NEW_TEST_LAST_NAME = "new_last_name"
IS_OPENID_USER = "is_openid_user"


# field
PASSWORD_FIELD = "password"
