# Constants for testing account management features in a Canvas project

TEST_EMAIL = "testuser@example.com"
TEST_USERNAME = "testuser"
SECURE_PASSWORD = "SecurePass123!"
TOO_SHORT_PASSWORD = "Save-1"
TEST_PASSWORD = "test"
UPDATED_PASSWORD = "NewSecurePassword123!"
RESET_PASSWORD = "SecurePass1234!"
NO_SPECIAL_CHAR_PASSWORD = "SecurePass123"
COMPLETELY_WRONG_PASSWORD = "securepassword"
NO_UPPERCASE_PASSWORD = "securepassword123!"
NO_LOWERCASE_PASSWORD = "SECUREPASSWORD123!"
MISMATCHED_BUT_CORRECT_PASSWORD = "NewSecurePassword123!!"
NO_NUMERIC_PASSWORD = "SecurePassword!"
MISMATCHED_BUT_CORRECT_PASSWORD_2 = "NewSecurePassword123!!!"
WRONG_LOGIN_PASSWORD = "WrongPassword123!"
