# Generated by Django 5.1.5 on 2025-02-04 14:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project_management", "0015_alter_project_preview"),
        ("project_management", "0016_alter_project_preview"),
    ]

    operations = []
