# Generated by Django 5.1.4 on 2025-02-04 17:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project_management", "0015_alter_project_preview"),
        ("project_management", "0016_alter_project_preview"),
        ("project_management", "0016_merge_20250202_1722"),
    ]

    operations = []
