# Generated by Django 5.1.4 on 2025-02-05 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project_management", "0017_merge_20250204_1431"),
        ("project_management", "0017_merge_20250204_1717"),
    ]

    operations = []
