# Generated by Django 5.1.5 on 2025-02-04 17:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project_management", "0017_merge_20250204_1427"),
    ]

    operations = []
