# Generated by Django 5.1.4 on 2025-02-05 18:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project_management", "0018_auto_20250204_1720"),
        ("project_management", "0018_merge_20250205_0828"),
    ]

    operations = []
