# Generated by Django 5.1.4 on 2025-02-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_management", "0018_merge_20250205_1606"),
    ]

    operations = [
        migrations.AddField(
            model_name="receiver",
            name="receiverType",
            field=models.CharField(default="planar", max_length=300),
        ),
    ]
