# Generated by Django 5.1.4 on 2025-02-05 16:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project_management", "0019_receiver_receivertype"),
    ]

    operations = [
        migrations.RenameField(
            model_name="receiver",
            old_name="receiverType",
            new_name="receiver_type",
        ),
    ]
