# Generated by Django 4.2.19 on 2025-02-06 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0012_merge_20250129_1859'),
        ('project_management', '0019_merge_20250205_1830'),
    ]

    operations = [
    ]
