# Generated by Django 5.1.6 on 2025-02-06 16:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project_management", "0012_merge_20250201_1459"),
        ("project_management", "0018_merge_20250205_1112"),
        ("project_management", "0020_merge_20250206_1518"),
    ]

    operations = []
