# Generated by Django 5.1.4 on 2025-02-05 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project_management", "0020_rename_receivertype_receiver_receiver_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receiver",
            name="receiver_type",
        ),
    ]
