# Generated by Django 5.1.6 on 2025-02-07 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project_management", "0021_merge_20250206_1644"),
        ("project_management", "0021_remove_receiver_receiver_type"),
    ]

    operations = []
