# Generated by Django 5.1.6 on 2025-02-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_management", "0022_merge_20250207_1047"),
    ]

    operations = [
        migrations.AddField(
            model_name="receiver",
            name="receiver_type",
            field=models.CharField(default="planar", max_length=300),
        ),
    ]
