# Generated by Django 5.2.7 on 2025-10-08 09:19

from django.db import migrations
from django.db.migrations.state import StateApps


def update_default_site(apps: StateApps, _) -> None:
    """Update the default name and URL of the Django site."""
    site = apps.get_model("sites", "Site")

    domain = "canvas-editor.org"
    name = "CANVAS"

    site.objects.update_or_create(pk=1, defaults={"domain": domain, "name": name})


class Migration(migrations.Migration):
    """Migration to execute the default site update function.

    Used to automatically set up the correct name and URL for the website. The URL and site name are used by allauth to display
    in the emails send to the user.
    """

    dependencies = [
        ("sites", "0001_initial"),
    ]

    operations = [migrations.RunPython(update_default_site)]
