# Generated by Django 5.2.7 on 2025-10-12 12:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "last_edited",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_shared", models.DateTimeField(blank=True, null=True)),
                ("favorite", models.BooleanField(default=False)),
                ("preview", models.ImageField(upload_to="project_previews/")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "owner")},
            },
        ),
        migrations.CreateModel(
            name="LightSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default="Light source", max_length=200
                    ),
                ),
                ("number_of_rays", models.IntegerField(default=100)),
                ("light_source_type", models.CharField(default="sun", max_length=300)),
                (
                    "distribution_type",
                    models.CharField(default="normal", max_length=300),
                ),
                ("mean", models.FloatField(default=0)),
                ("covariance", models.FloatField(default=4.3681e-06)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="light_sources",
                        to="project_management.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Heliostat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, default="Heliostat", max_length=200),
                ),
                ("position_x", models.FloatField(default=0)),
                ("position_y", models.FloatField(default=0)),
                ("position_z", models.FloatField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heliostats",
                        to="project_management.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Receiver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, default="Receiver", max_length=200),
                ),
                ("position_x", models.FloatField(default=0)),
                ("position_y", models.FloatField(default=50)),
                ("position_z", models.FloatField(default=0)),
                ("normal_x", models.FloatField(default=0)),
                ("normal_y", models.FloatField(default=1)),
                ("normal_z", models.FloatField(default=0)),
                ("receiver_type", models.CharField(default="planar", max_length=300)),
                ("plane_e", models.FloatField(default=8.629666667)),
                ("plane_u", models.FloatField(default=7.0)),
                ("resolution_e", models.IntegerField(default=256)),
                ("resolution_u", models.IntegerField(default=256)),
                ("curvature_e", models.FloatField(default=0)),
                ("curvature_u", models.FloatField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receivers",
                        to="project_management.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shadows", models.BooleanField(default=True)),
                ("fog", models.BooleanField(default=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="project_management.project",
                    ),
                ),
            ],
        ),
    ]
