name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11, 3.12, 3.13]

    steps:
      - uses: actions/checkout@v4
      - name: Set up ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
      - name: Run Tests
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          mkdir -p ../reports

          coverage run manage.py test \
            --noinput \
            --verbosity=2 \
            --testrunner=xmlrunner.extra.djangotestrunner.XMLTestRunner \
            --pattern="test*.py"

          mv TEST-*.xml ../reports/ || true

          coverage xml -o ../reports/coverage.xml
      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-py${{ matrix.python-version }}
          path: reports/**/*.xml
